### ISSUE TITLE
Beam Search是怎么运用的？

### ISSUE THREAD

**Issue by keaixiaovv** [312shan/Pytorch-seq2seq-Beam-Search#1]
您好，我最近在看您代码Seq2Seq中的BeamSearch，请问beam_decode函数返回的decoded_batch是怎么运用的？
我只在测试的代码中看到有调用，但是没看到有后续的操作了
![image](https://user-images.githubusercontent.com/49025537/112249938-90104a80-8c93-11eb-9890-edd36d30a6c9.png)

**Comment by 312shan** [comment]
你好，通过 decoded_batch 可以映射得到翻译之后的句子。只不过 beam-search 不参与 loss 计算所以在这里没有被使用。

**Comment by keaixiaovv** [comment]
这里的decoded_batch 返回的是字典中单词的编号吗？请问怎么映射成句子呢？

**Comment by 312shan** [comment]
@keaixiaovv 可以参考新增的这几行代码，会解码和打印部分翻译结果。 https://github.com/312shan/Pytorch-seq2seq-Beam-Search/blob/a55ce371614da7b9bb1d96de6d0089dabaaa3ac2/train.py#L46

**Comment by 312shan** [comment]
问题已解决。
