### ISSUE TITLE
decode 未 return

### ISSUE THREAD

**Issue by kaihe** [312shan/Pytorch-seq2seq-Beam-Search#2]
![image](https://user-images.githubusercontent.com/7460776/114966954-29530b00-9ea6-11eb-97df-90fe0b4abe13.png)

seq2seq.decode() 方法没return beam 或 greedy decode 的结果

**Comment by 312shan** [comment]
@kaihe 感谢指出问题，已经做了修改，并且添加了解码打印翻译结果的的例子。https://github.com/312shan/Pytorch-seq2seq-Beam-Search/blob/a55ce371614da7b9bb1d96de6d0089dabaaa3ac2/train.py#L46

**Comment by 312shan** [comment]
问题已解决。

**Comment by 312shan** [comment]
问题已解决。

**Comment by 312shan** [comment]
问题已解决。
